### ISSUE TITLE
On September 14th, 2022, Datatrans will enforce the latest security standards for all merchants. Therefore, adjustments to your technical integration are necessary.

### ISSUE THREAD

**Issue by Axent96** [academe/omnipay-datatrans#12]
we need now to have password field to be able to generate the "Authorization" header.

### Authentication to the APIs is performed via HTTP Basic Auth. Provide your merchantId as the basic auth username value. Login to Webadmin to enable server to server security under UPP Administrations > Security and generate your password.

Before enabling basic authentication for an existing merchantId please make sure your current integration already sends the correct Authorization header.
Create a base64 encoded value of merchantId and password (most HTTP clients are able to handle the base64 encoding automatically) and submit the Authorization header with each request. For example:

base64(merchantId:password) = MTAwMDAxMTAxMTpYMWVXNmkjJA==
Authorization: Basic MTAwMDAxMTAxMTpYMWVXNmkjJA==
All API requests must be done over HTTPS with TLS >= 1.2.

Here is more information https://api-reference.datatrans.ch/xml/#request-signing

**Comment by Axent96** [comment]
@judgej  I found a solution for the issue in PR #9  of issue #8

**Comment by judgej** [comment]
PR #9 got rather forgotten about. I'm happy to merge it, based on your confirmation that it doesn't break existing functionality. If you are using that PR as-is, with no issues, let me know and I'll merge and tag it for a minor release.

I don't have a test setup right now to test it myself.

**Comment by Axent96** [comment]
@judgej It works for me. Thank you very much!

**Comment by judgej** [comment]
Thank @gallib for that!

I've merged and made a minor release. Any issues, I'll try to fix as quickly as I can.

**Comment by Axent96** [comment]
@judgej do you can add please a tag for last commit of master branch for the minor release?

**Comment by judgej** [comment]
Done: https://github.com/academe/omnipay-datatrans/releases/tag/3.1.0
