### ISSUE TITLE
3.1 throws [Warning] hex2bin(): Input string must be hexadecimal string

### ISSUE THREAD

**Issue by lerni** [academe/omnipay-datatrans#13]
3.1 or since https://github.com/academe/omnipay-datatrans/commit/98fd4536561e3576ee013d7d497bc5f8d41ce6ba PHP74 & PHP80 both throw a [Warning] like:
```
[Warning] hex2bin(): Input string must be hexadecimal string
Line 88 in /var/www/html/vendor/academe/omnipay-datatrans/src/Message/AbstractRequest.php
```

**Comment by lerni** [comment]
Yes and it was triggered by using quotes in docker-file / env file. Thanks answering so fast. closing :runner:

**Comment by judgej** [comment]
No problem. That particular issue of docker compose and laravel (through the dotenv package) handing quoted .env values completely differently, is a trap that many have fallen into, me included.
